#! /usr/bin/env bash
set -euf -o pipefail

compile() {
    OS=${1:?usage: specify os}
    rm -rf tmp/travis
    mkdir -p tmp/travis
    cp .travis.$OS.yml tmp/travis/.travis.yml
    
    (cd tmp/travis && TRAVIS_BUILD_APT_PACKAGE_WHITELIST=https://raw.githubusercontent.com/travis-ci/apt-package-whitelist/master/ubuntu-precise travis compile > ../../build.$OS.sh)
    chmod +x build.$OS.sh
}
compile osx
compile linux
