* Boot React Native
Provides several tasks that helps integrate ClojureScript with the React Native packager and build process
** Why?
React Native and ClojureScript seem to be made for each other. Unfortunately, out of the box ClojureScript does not play nice with React Native.

Basically, trying to get them to work together leads to the following problems:
 * You have to set up the cljs compiler to use :optimizations :whitespace or higher - this leads to slow compilation (more than 30 seconds after each change on my PC)
 * boot-reload and boot-cljs-repl tasks do not work
 * You have to start up the React Native packager in a separate terminal

This library aims to fix all of the above. It:
 * Allows for builds with :optimizations :none - much faster builds, and 1-2 second rebuilds
 * Allows for integration with other cljs boot tasks - cljs-repl, reload, cljs-test
 * Provides tasks to auto start react native packager
 * Custom transformer for react-native to speed up builds significantly
 * Logging server to allow for capturing console.log output on command line
** How to use?
Simply add the tasks =(react-native-devenv)= and =(start-rn-packager)= to the end of your build tasks, and =(shim-boot-reload)= to just after the reload task. There is an example in the example directory that illustrates this - here's the main task from the example:

#+BEGIN_SRC clojure
(deftask fast-build []
  (comp (serve :handler 'mattsum.simple-log-server/log
               :port 8000)
        (watch)
        (reload :on-jsload 'mattsum.simple-example.core/on-js-reload
                :port 8079
                :ws-host "matt-dev"
                )
        (rn/shim-boot-reload)

        (cljs-repl :ws-host "matt-dev"
                   :ip "0.0.0.0")

        (cljs :main "mattsum.simple-example.core")
        (rn/react-native-devenv :server-url "matt-dev:8081")
        (rn/start-rn-packager)
        ))
#+END_SRC

* License

Copyright © 2015 Matt Meintjes

Distributed under the Eclipse Public License, the same as Clojure.
